[Definition]
failregex = ^<HOST>.*"(GET|POST|HEAD).*(/cgi-bin/|/vendor/|/\.env|/\.git|/wp-admin|/wp-login|/wp-content|/wp-includes|/phpmyadmin|/admin/config|/manager/html|/console/|/actuator|/api/v1/pods|/owa/|/ecp/|/autodiscover|/boaform|/HNAP1|/setup\.cgi|/dns-query|/\.well-known/openid|/_ignition|/server-status|/server-info|/eval-stdin\.php).*" (4\d\d|5\d\d).*$
ignoreregex =
