#!/bin/bash
# ============================================================================
# notify.sh — отправка уведомлений в Telegram
#
# Использование:
#   source /opt/appaz-vpn/deploy/lib/notify.sh
#   tg_notify "Server is up"
#   tg_notify_md "*Bold* and _italic_ message"
#   tg_notify_error "Something broke" "$error_details"
# ============================================================================

NOTIFY_ENV_FILE="${NOTIFY_ENV_FILE:-/etc/appaz/notify.env}"

# Загружаем переменные из файла если он есть
if [ -f "$NOTIFY_ENV_FILE" ]; then
    # shellcheck disable=SC1090
    source "$NOTIFY_ENV_FILE"
fi

# Базовая функция отправки. Тихо проглатывает ошибки сети.
# Возвращает 0 если TG_BOT_TOKEN/TG_CHAT_ID не заданы (graceful no-op).
_tg_send() {
    local text="$1"; local parse_mode="${2:-}"
    if [ -z "${TG_BOT_TOKEN:-}" ] || [ -z "${TG_CHAT_ID:-}" ]; then
        return 0
    fi
    local args=(-s -m 10 -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage")
    args+=(-d "chat_id=${TG_CHAT_ID}")
    args+=(--data-urlencode "text=${text}")
    [ -n "$parse_mode" ] && args+=(-d "parse_mode=${parse_mode}")
    curl "${args[@]}" >/dev/null 2>&1 || true
}

# Обычное текстовое сообщение
tg_notify() {
    _tg_send "$1"
}

# Сообщение в Markdown
tg_notify_md() {
    _tg_send "$1" "MarkdownV2"
}

# Сообщение об ошибке с заголовком и деталями
tg_notify_error() {
    local title="$1"; local details="${2:-}"
    local msg="❌ ERROR: ${title}"
    [ -n "$details" ] && msg="${msg}

Details:
${details}"
    _tg_send "$msg"
}

# Сообщение об успехе
tg_notify_ok() {
    _tg_send "✅ $1"
}

# Сохранить notify-конфиг (интерактивно или из env)
tg_save_config() {
    mkdir -p "$(dirname "$NOTIFY_ENV_FILE")"
    cat > "$NOTIFY_ENV_FILE" <<CFG
# Telegram notifications config
# Generated by deploy.sh
TG_BOT_TOKEN="${TG_BOT_TOKEN}"
TG_CHAT_ID="${TG_CHAT_ID}"
CFG
    chmod 600 "$NOTIFY_ENV_FILE"
}
